
Description: >
    Role Resource example
#  by wolfgang unger 9.12.2018

Resources:
  JenkinsRole:
    Type: 'AWS::IAM::Role'
    Properties:
        RoleName: JenkinsRole    
        Path: "/"     
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "ec2.amazonaws.com"
              Action: 
                  - "sts:AssumeRole"
        ManagedPolicyArns:
            - arn:aws:iam::906781655012:policy/customer/ecs-service






