---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      #AvailabilityZone: us-east-1a
      # us east image
      #ImageId: ami-a4c7edb2
      # eu west 2 image
      #ImageId: ami-403e2524
      # eu-central-1
      ImageId: ami-030aae8cba933aede
      InstanceType: t2.micro

