output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = "${module.eks.cluster_endpoint}"
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = "${module.eks.kubeconfig}"
}
